### ISSUE TITLE
Channels are not shown correctly

### ISSUE THREAD

**Issue by istankovic** [raiden-network/explorer#282] opened 2021-05-31 12:10 UTC
When looking at node `0x8c31290358f6855bAf060e6FA7b11517444641e3` at https://explorer.raiden.network/tokens/0x6B175474E89094C44Da98b954EedeAC495271d0F, I can see 3 channels with the "Show all channels" enabled.
However, notice that the tooltip shows 4 settled channels.

The `v1/channels` endpoint on the local Raiden node returns:
```
[{"state": "opened", "partner_address": "0x24EF85F0175545849A12bf74EFAedDA2E7e8C7D9", "token_network_address": "0xEA92bD481e54BBB9Bb6C927970a54E82eE26c6B4", "token_address": "0x6B175474E89094C44Da98b954EedeAC495271d0F", "total_deposit": "29000000000000000000", "settle_timeout": "100", "reveal_timeout": "50", "balance": "29000000000000000000", "channel_identifier": "94", "total_withdraw": "0", "network_state": "unknown"}]
```
Note that the tooltip says that the number of open channels is 0.

Additionally, if "Show all channels" is disabled, the node is not shown at all -- probably related to the above issue where the explorer thinks that the number of open channels is 0.

**Comment by fredo** [comment] 2021-05-31 12:21
I also see the following: 

I enabled `show all` and see two completely disjunct channels where the same address is a channel partner `0x95b2485Da3186337dAD276e7A96799bddF00C168`

**Comment by manuelwedler** [comment] 2021-06-24 11:28
At the moment it seems like this issue is not present anymore. I tried to reproduce the issue by running the Explorer until the block of that time and I didn't experienced any channels being shown incorrectly.

As the issue is not there anymore and it is not possible to reproduce it, I am closing.

**Closed by manuelwedler** 2021-06-24 11:28 UTC
Labels: bug
